"""
report_generator.py
Generates PDF diagnosis reports using ReportLab.
"""

import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                Table, TableStyle, HRFlowable)


def generate_pdf_report(history_rows: list, output_path: str) -> str:
    """
    Generate a PDF report of diagnosis history.
    Returns the saved file path.
    """
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    blue = colors.HexColor("#2563EB")
    light_blue = colors.HexColor("#EFF6FF")

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        textColor=blue,
        fontSize=22,
        spaceAfter=6,
    )
    sub_style = ParagraphStyle(
        "Sub",
        parent=styles["Normal"],
        textColor=colors.HexColor("#64748B"),
        fontSize=11,
        spaceAfter=16,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
    )

    story = []

    # Header
    story.append(Paragraph("IntelliExpert AI", title_style))
    story.append(Paragraph("Medical Diagnosis Report", sub_style))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", body_style))
    story.append(HRFlowable(width="100%", thickness=1, color=blue, spaceAfter=16))

    if not history_rows:
        story.append(Paragraph("No diagnosis records found.", body_style))
    else:
        # Table
        table_data = [["#", "Timestamp", "Symptoms", "Diagnosis", "Confidence"]]
        for row in history_rows:
            table_data.append([
                str(row[0]),
                str(row[1]),
                str(row[2])[:60] + ("…" if len(str(row[2])) > 60 else ""),
                str(row[3]).title(),
                f"{float(row[4]):.1f}%" if row[4] else "N/A",
            ])

        t = Table(table_data, colWidths=[1 * cm, 3.5 * cm, 6 * cm, 3.5 * cm, 2.5 * cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), blue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, light_blue]),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#E2E8F0")),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)

    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E1")))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        "⚠️ This report is generated by an AI system for educational/research purposes only. "
        "Always consult a licensed medical professional for clinical decisions.",
        ParagraphStyle("Disclaimer", parent=styles["Normal"], fontSize=8,
                       textColor=colors.HexColor("#94A3B8"), leading=12),
    ))

    doc.build(story)
    return output_path
